### PR TITLE
Developer

### LINKED ISSUE #6: Upgrade design of the app

### PR DESCRIPTION
**Pull request by StoyanTinchev**
Fixes #6 and #2 issues

### CODE REVIEW

**Comment by alexander24032003** [comment]
It's ok.

**Comment by alexander24032003** [comment]
Seems fine.

**Comment by alexander24032003** [comment]
Its ok.

**Comment by StoyanTinchev** [comment]
Review

**Review by alexander24032003 — APPROVED** [review]
Bravo!

**Pull request merged**
